[2024-12-23 14:20:41,333: INFO: main: >>> stage Data Ingestion Stage started <<<]
[2024-12-23 14:20:41,333: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-12-23 14:20:41,334: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-23 14:20:41,334: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-12-23 14:20:41,334: INFO: common: Created directory at: artifacts]
[2024-12-23 14:20:41,334: INFO: common: Created directory at: artifacts/data_ingestion]
[2024-12-23 14:20:41,335: ERROR: main: 'DataIngestionConfig' object has no attribute 'local_date_file']
Traceback (most recent call last):
  File "/home/deepak/Desktop/projcts/MLops_projects/Datascience_Project_1/main.py", line 8, in <module>
    obj.initiate_data_ingestion()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/deepak/Desktop/projcts/MLops_projects/Datascience_Project_1/src/Datascience_1/pipeline/data_ingestion_pipeline.py", line 15, in initiate_data_ingestion
    data_ingestion.download_file()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/deepak/Desktop/projcts/MLops_projects/Datascience_Project_1/src/Datascience_1/components/data_ingestion.py", line 18, in download_file
    filename=self.config.local_date_file
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataIngestionConfig' object has no attribute 'local_date_file'. Did you mean: 'local_data_file'?
[2024-12-23 14:21:15,166: INFO: main: >>> stage Data Ingestion Stage started <<<]
[2024-12-23 14:21:15,167: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-12-23 14:21:15,167: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-23 14:21:15,168: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-12-23 14:21:15,168: INFO: common: Created directory at: artifacts]
[2024-12-23 14:21:15,168: INFO: common: Created directory at: artifacts/data_ingestion]
[2024-12-23 14:21:16,484: ERROR: main: [Errno 2] No such file or directory: 'artfacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "/home/deepak/Desktop/projcts/MLops_projects/Datascience_Project_1/main.py", line 8, in <module>
    obj.initiate_data_ingestion()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/deepak/Desktop/projcts/MLops_projects/Datascience_Project_1/src/Datascience_1/pipeline/data_ingestion_pipeline.py", line 15, in initiate_data_ingestion
    data_ingestion.download_file()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/deepak/Desktop/projcts/MLops_projects/Datascience_Project_1/src/Datascience_1/components/data_ingestion.py", line 16, in download_file
    filename, headers = request.urlretrieve(
                        ~~~~~~~~~~~~~~~~~~~^
        url=self.config.source_URL,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        filename=self.config.local_data_file
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/deepak/anaconda3/envs/mlops/lib/python3.13/urllib/request.py", line 224, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'artfacts/data_ingestion/data.zip'
[2024-12-23 14:29:13,928: INFO: main: >>> stage Data Ingestion Stage started <<<]
[2024-12-23 14:29:13,929: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-12-23 14:29:13,930: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-23 14:29:13,930: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-12-23 14:29:13,930: INFO: common: Created directory at: artifacts]
[2024-12-23 14:29:13,930: INFO: common: Created directory at: artifacts/data_ingestion]
[2024-12-23 14:29:14,593: ERROR: main: [Errno 2] No such file or directory: 'artfacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "/home/deepak/Desktop/projcts/MLops_projects/Datascience_Project_1/main.py", line 8, in <module>
    obj.initiate_data_ingestion()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/deepak/Desktop/projcts/MLops_projects/Datascience_Project_1/src/Datascience_1/pipeline/data_ingestion_pipeline.py", line 15, in initiate_data_ingestion
    data_ingestion.download_file()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/deepak/Desktop/projcts/MLops_projects/Datascience_Project_1/src/Datascience_1/components/data_ingestion.py", line 16, in download_file
    filename, headers = request.urlretrieve(
                        ~~~~~~~~~~~~~~~~~~~^
        url=self.config.source_URL,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        filename=self.config.local_data_file
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/deepak/anaconda3/envs/mlops/lib/python3.13/urllib/request.py", line 224, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'artfacts/data_ingestion/data.zip'
[2024-12-23 14:33:19,321: INFO: main: >>> stage Data Ingestion Stage started <<<]
[2024-12-23 14:33:19,321: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-12-23 14:33:19,322: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-23 14:33:19,322: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-12-23 14:33:19,322: INFO: common: Created directory at: artifacts]
[2024-12-23 14:33:19,322: INFO: common: Created directory at: artifacts/data_ingestion]
[2024-12-23 14:33:20,834: ERROR: main: [Errno 2] No such file or directory: 'artfacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "/home/deepak/Desktop/projcts/MLops_projects/Datascience_Project_1/main.py", line 8, in <module>
    obj.initiate_data_ingestion()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/deepak/Desktop/projcts/MLops_projects/Datascience_Project_1/src/Datascience_1/pipeline/data_ingestion_pipeline.py", line 15, in initiate_data_ingestion
    data_ingestion.download_file()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/deepak/Desktop/projcts/MLops_projects/Datascience_Project_1/src/Datascience_1/components/data_ingestion.py", line 16, in download_file
    filename, headers = request.urlretrieve(
                        ~~~~~~~~~~~~~~~~~~~^
        url=self.config.source_URL,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        filename=self.config.local_data_file
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/deepak/anaconda3/envs/mlops/lib/python3.13/urllib/request.py", line 224, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'artfacts/data_ingestion/data.zip'
[2024-12-23 14:43:12,487: INFO: main: >>> stage Data Ingestion Stage started <<<]
[2024-12-23 14:43:12,488: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-12-23 14:43:12,488: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-23 14:43:12,489: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-12-23 14:43:12,489: INFO: common: Created directory at: artifacts]
[2024-12-23 14:43:12,489: INFO: common: Created directory at: artifacts/data_ingestion]
[2024-12-23 14:43:13,175: INFO: data_ingestion: artfacts/data_ingestion/data.zip Downloaded with the following info:
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 3769:20B0B0:46FE5:5AD9C:676971DB
Accept-Ranges: bytes
Date: Mon, 23 Dec 2024 14:43:13 GMT
Via: 1.1 varnish
X-Served-By: cache-lon420102-LON
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1734964993.942726,VS0,VE138
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: d895ebe3001618d19f66d86d7efd994804c64557
Expires: Mon, 23 Dec 2024 14:48:13 GMT
Source-Age: 0

]
[2024-12-23 14:43:13,178: INFO: main: >>> stage Data Ingestion Stage completed <<<]
[2024-12-23 14:46:03,462: INFO: main: >>> stage Data Ingestion Stage started <<<]
[2024-12-23 14:46:03,463: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-12-23 14:46:03,464: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-23 14:46:03,464: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-12-23 14:46:03,464: INFO: common: Created directory at: artifacts]
[2024-12-23 14:46:03,464: INFO: common: Created directory at: artifacts/data_ingestion]
[2024-12-23 14:46:04,195: INFO: data_ingestion: artifacts/data_ingestion/data.zip Downloaded with the following info:
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 3769:20B0B0:46FE5:5AD9C:676971DB
Accept-Ranges: bytes
Date: Mon, 23 Dec 2024 14:46:04 GMT
Via: 1.1 varnish
X-Served-By: cache-lon4266-LON
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1734965164.173347,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 0966c26c36f19187eda06a9176a30d1f4f4d7de6
Expires: Mon, 23 Dec 2024 14:51:04 GMT
Source-Age: 171

]
[2024-12-23 14:46:04,200: INFO: main: >>> stage Data Ingestion Stage completed <<<]
